# Generated by Django 6.0.2 on 2026-02-20 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance_employees_a_employe_b62a87_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('assignment', 'Assignment'), ('exam', 'Exam/Test'), ('report', 'Report'), ('curriculum', 'Curriculum Document'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='teacher_submissions/')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Needs Revision')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['teacher', 'status'], name='employees_w_teacher_1ebffc_idx'), models.Index(fields=['status'], name='employees_w_status_6c9e1a_idx'), models.Index(fields=['-submitted_at'], name='employees_w_submitt_c90a81_idx'), models.Index(fields=['work_type'], name='employees_w_work_ty_3ec15b_idx')],
            },
        ),
    ]
