# Generated by Django 6.0.2 on 2026-02-20 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_worksubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='submitted_to',
            field=models.ForeignKey(blank=True, help_text='Head of Class or Director who receives this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['submitted_to', 'status'], name='employees_w_submitt_925da1_idx'),
        ),
    ]
