# Generated by Django 6.0.2 on 2026-02-19 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current'], name='fees_academ_is_curr_6f1093_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['-start_date'], name='fees_academ_start_d_451052_idx'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['student', 'is_paid'], name='fees_feebal_student_2da5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['is_paid', 'due_date'], name='fees_feebal_is_paid_43fc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['-created_at'], name='fees_feebal_created_e637db_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student', 'fee_structure'], name='fees_feepay_student_9cc7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_status'], name='fees_feepay_payment_90881c_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['-payment_date'], name='fees_feepay_payment_e36619_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_number'], name='fees_feepay_receipt_5b901a_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['-created_at'], name='fees_feepay_created_a91781_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['academic_year', 'grade'], name='fees_feestr_academi_31cf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='fees_feestr_is_acti_c62141_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['-created_at'], name='fees_feestr_created_541e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['level'], name='fees_grade_level_58a20f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='fees_studen_admissi_1314d9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='fees_studen_status_88aebe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'status'], name='fees_studen_grade_i_dd6b17_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='fees_studen_first_n_315fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-created_at'], name='fees_studen_created_ccc971_idx'),
        ),
    ]
