# Generated by Django 6.0.2 on 2026-02-21 08:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_academicyear_fees_academ_is_curr_6f1093_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feebalance',
            name='amount_after_scholarship',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after scholarship discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='feebalance',
            name='scholarship_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Scholarship discount amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Scholarship percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_remarks',
            field=models.TextField(blank=True, help_text='Scholarship details and conditions'),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_status',
            field=models.CharField(choices=[('none', 'No Scholarship'), ('partial', 'Partial Scholarship'), ('full', 'Full Scholarship')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='feebalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['scholarship_status'], name='fees_studen_scholar_186022_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'scholarship_status'], name='fees_studen_status_46a8c8_idx'),
        ),
    ]
