# Generated by Django 6.0.2 on 2026-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feebalance_amount_after_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any known allergies'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, help_text='e.g., A+, O-, AB+', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any chronic conditions or special needs'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/others/'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_report_card',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/report_cards/'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/transfers/'),
        ),
    ]
