# Generated by Django 6.0.2 on 2026-02-20 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('director', 'Director'), ('teacher', 'Teacher'), ('security', 'Security'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('receptionist', 'Receptionist'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_f8a1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='accounts_us_role_e16858_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active_employee'], name='accounts_us_is_acti_a09e13_idx'),
        ),
    ]
