# Generated by Django 6.0.2 on 2026-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(blank=True, help_text='Class assigned to Head of Class or Teacher (e.g., Grade 1A, Grade 2B)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('director', 'Director'), ('head_of_class', 'Head of Class'), ('teacher', 'Teacher'), ('security', 'Security'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('receptionist', 'Receptionist'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
