# Generated by Django 6.0.2 on 2026-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_class_name_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('director', 'Director'), ('head_of_class', 'Head of Class'), ('teacher', 'Teacher'), ('security', 'Security'), ('bursar', 'Bursar'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('receptionist', 'Receptionist'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
