# Generated by Django 6.0.2 on 2026-02-21 08:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0004_student_allergies_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('cat', 'Continuous Assessment Test'), ('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('mock', 'Mock Exam')], max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_marks', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='fees.academicyear')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Pass'), ('F', 'F - Fail')], max_length=1)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='fees.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='fees.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Pass'), ('F', 'F - Fail')], max_length=1)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='fees.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['student', 'exam'], name='academics_m_student_b5b37d_idx'), models.Index(fields=['exam', 'subject'], name='academics_m_exam_id_5cbb53_idx')],
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='fees.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='fees.grade')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='academics.subject')),
            ],
            options={
                'ordering': ['grade', 'subject'],
                'unique_together': {('grade', 'subject', 'academic_year')},
            },
        ),
    ]
